using GraphitiNet.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace GraphitiNet.Abstractions;

/// <summary>
/// Defines the contract for a service that handles the extraction of
/// graph elements (entities, relationships) from content.
/// </summary>
public interface IExtractionService
{
    /// <summary>
    /// Extracts entities from the content of an episodic node, generates embeddings for them,
    /// saves them to the database, and links them to the source episodic node.
    /// </summary>
    /// <param name="episodicNode">The source episodic node containing the content to process.</param>
    /// <param name="targetEntityLabels">A list of entity labels to target for extraction (e.g., "Person", "Organization").</param>
    /// <returns>A list of created or updated <see cref="EntityNode"/>s that were extracted and processed.</returns>
    Task<List<EntityNode>> ExtractAndLinkEntitiesAsync(EpisodicNode episodicNode, List<string> targetEntityLabels);

    /// <summary>
    /// Extracts relationships between a list of pre-identified entities based on the content of an episodic node.
    /// It generates embeddings for these relationships, saves them, and links them to the source episodic node.
    /// </summary>
    /// <param name="episodicNode">The source episodic node containing the content and reference time.</param>
    /// <param name="extractedEntities">A list of entities already extracted from this episodic node.</param>
    /// <param name="targetRelationshipTypes">A list of relationship types to target for extraction (e.g., "WORKS_FOR", "LOCATED_IN").</param>
    /// <returns>A list of created or updated <see cref="EntityEdge"/>s that were extracted.</returns>
    Task<List<EntityEdge>> ExtractRelationshipsAsync(
        EpisodicNode episodicNode,
        List<EntityNode> extractedEntities,
        List<string> targetRelationshipTypes);
}
```

**Notes on Handling Potential Issues (MVP):**

*   **Entities Not Found (from DTO `source_entity_name` / `target_entity_name`):**
    *   The implementation uses a dictionary (`entityLookup`) for efficient lookup of `EntityNode.Id` by `EntityNode.Name`.
    *   If a name from the DTO is not found in this lookup (or if multiple entities have the same name, which this simple lookup doesn't handle disambiguation for), a warning is logged, and that specific relationship DTO is skipped.
    *   For MVP, this is a reasonable approach. More advanced logic could involve fuzzy matching, or the LLM could be prompted to return entity IDs if they were passed into the prompt (but that adds complexity to the prompt and requires entities to be saved *before* relationship extraction if IDs are generated by the DB).

*   **Date Parsing Errors (`valid_at`, `invalid_at`):**
    *   The `TryParseIsoDateTime` helper method attempts to parse ISO 8601 strings.
    *   It tries `DateTime.TryParse` with `AdjustToUniversal` and `AssumeUniversal` styles, which is quite flexible for ISO 8601.
    *   It also includes a fallback for "yyyy-MM-dd" format.
    *   If parsing fails, a warning is logged, and the corresponding `DateTime?` property on `EntityEdge` remains `null`.
    *   For MVP, this is acceptable. The LLM is instructed to provide ISO 8601, but robustness to minor variations or failures is handled by defaulting to null.

*   **Reflexive Relationships:**
    *   The code now includes a check to skip relationships where the source and target entity are the same.

*   **Normalization:**
    *   Entity names from DTOs are trimmed (`dto.SourceEntityName.Trim()`).
    *   Relationship types are trimmed and converted to uppercase (`dto.RelationshipType.Trim().ToUpperInvariant()`) for consistency.

*   **Error during Embedding/Saving:**
    *   If embedding generation for a fact fails, a warning is logged, and the edge is saved without an embedding (MVP approach).
    *   If saving an edge to the database fails, a warning is logged, and the process continues with the next DTO.

This implementation provides the core logic for relationship extraction as defined for the MVP.
The `ExtractionPrompts.RelationshipExtractionTemplate` constant is assumed to be present in `GraphitiNet/Prompts/ExtractionPrompts.cs` for the code to compile and run correctly.
The `IGraphDatabaseService` is assumed to have the `AddOrUpdateEdgeAsync(BaseEdge edge)` method for saving the `EntityEdge`.
