using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace GraphitiNet.Models;

/// <summary>
/// Represents an entity in the knowledge graph.
/// Entities are the core concepts or objects, such as persons, organizations, locations, or abstract ideas.
/// </summary>
public record EntityNode : BaseNode
{
    /// <summary>
    /// The primary human-readable name or identifier for the entity.
    /// This is often the main piece of text used for identifying and searching for the entity.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// An optional summary or description of the entity.
    /// This could be a brief overview, potentially generated by an LLM or extracted from source text.
    /// </summary>
    [JsonPropertyName("summary")]
    public string? Summary { get; init; }

    /// <summary>
    /// Optional vector embedding of the entity's <see cref="Name"/> or a combination of its defining text.
    /// Used for semantic search and similarity calculations.
    /// </summary>
    [JsonPropertyName("nameEmbedding")]
    public float[]? NameEmbedding { get; init; }

    /// <summary>
    /// Initializes a new instance of the <see cref="EntityNode"/> class.
    /// Automatically adds "Entity" as the primary label.
    /// </summary>
    public EntityNode()
    {
        // Ensure "Entity" is the primary label, users can add more specific labels.
        Labels = new List<string> { "Entity" };
    }
}
